apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebook-deployment
  labels:
    app: phonebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phonebook
  template:
    metadata:
      labels:
        app: phonebook
    spec:
      containers:
        - name: phonebook
          image: pincher95/crud_flask:latest
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
---
kind: Service
apiVersion: v1
metadata:
  name: phonebook-service
spec:
  type: ClusterIP
  selector:
    app: phonebook
  ports:
    - port: 8181 # Default port for image
      targetPort: 8181
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: phonebook-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - anthonycornell.com
      secretName: tls-secret
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: phonebook-service
              servicePort: 8181
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: phonebook
#  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: phonebook
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75