apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  annotations:
    "consul.hashicorp.com/connect-inject": "false"
  namespace: default
spec:
  containers:
    - name: dnsutils
      image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always